language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - gh-pages

notifications:
  email: false

before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle

script: ./gradlew clean assemble lintDevRelease testDevDebug

sudo: false

cache:
  directories:
    - $HOME/.m2